name: Convert Obsidian Vault for GitHub

on:
  push:
    branches: [main]

jobs:
  export-wiki:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install obsidian-export
        run: pip install obsidian-export

      - name: Run export
        run: |
          mkdir -p exported
          obsidian-export . exported --frontmatter=auto --embed-images

      - name: Commit exported markdown
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add exported
          git diff --quiet && git diff --staged --quiet || git commit -m "Exported GitHub-friendly markdown"
          git push

